---
# tasks file for roles/clickhause
# - name: Display facts
#   debug:
#     var: ansible_facts
#   when: ansible_pkg_mgr == "apt"

- name: SYSTEM | Update DNF repo for CentOS 8
  ansible.builtin.include_tasks: dnf_prepare.yml
  when: ansible_pkg_mgr == "dnf"

- name: SYSTEM | Prepare systems
  ansible.builtin.include_tasks: pre_task.yml

- name: CLICKHOUSE | Get distribs
  block:
    - name: Get clickhouse distrib for packages
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_ver }}_amd64.deb"
        dest: "/tmp/{{ item }}_{{ clickhouse_ver }}.deb"
        mode: "0644"
      with_items: "{{ clickhouse_packages }}"
  rescue:
    - name: Get clickhouse distrib for common static
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_ver }}_amd64.deb"
        dest: "/tmp/clickhouse-common-static_{{ clickhouse_ver }}.deb"
        mode: "0644"
  when: ansible_os_family == "Debian"

- name: CLICKHOUSE | Get distribs
  block:
    - name: Get clickhouse distrib for packages
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_ver }}.{{ ansible_architecture}}.rpm"
        dest: "/tmp/{{ item }}_{{ clickhouse_ver }}.rpm"
        mode: "0644"
      with_items: "{{ clickhouse_packages }}"
  when: ansible_os_family == "RedHat"

- name: CLICKHOUSE | Install packages
  become: true
  block:
    - name: CLICKHOUSE | Install packages on Debian Family
      become: true
      ansible.builtin.apt:
        deb: "/tmp/{{ item }}_{{ clickhouse_ver }}.deb"
        state: present
      with_items: "{{ clickhouse_packages }}"
      when: ansible_os_family == "Debian"
    - name: CLICKHOUSE | Install packages on RedHat Family (YUM)
      become: true
      ansible.builtin.yum:
        name: "/tmp/{{ item }}_{{ clickhouse_ver }}.rpm"
        state: present
      with_items: "{{ clickhouse_packages }}"
      when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum"
    - name: CLICKHOUSE | Install packages on RedHat Family (DNF)
      ansible.builtin.dnf:
        name: "/tmp/{{ item }}_{{ clickhouse_ver }}.rpm"
        state: present
        disable_gpg_check: true
      with_items: "{{ clickhouse_packages }}"
      when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf"

- name: CLICKHOUSE | Configure
  block:
    - name: CLICKHOUSE | Configurate
      become: true
      ansible.builtin.template:
        src: clickhouse.config.j2
        dest: "{{ clickhouse_config }}"
        mode: "0644"
    - name: CLICKHOUSE | Add user
      become: true
      ansible.builtin.template:
        src: clickhouse.users.j2
        dest: "{{ clickhouse_users }}"
        mode: "0644"

- name: CLICKHOUSE | Restarted service
  include_tasks: service.yml

- name: CLICKHOUSE | Create db and table
  block:
    - name: Create database
      ansible.builtin.command: clickhouse-client -q 'CREATE DATABASE logs;'
      register: create_db
      failed_when: create_db.rc != 0  and create_db.rc != 82
      changed_when: create_db.rc == 0
    - name: Create table
      ansible.builtin.command: clickhouse-client -q 'CREATE TABLE logs.file ("file" String, "host" String, "message" String, "timestamp" DateTime) Engine=Log;'
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc != 57
      changed_when: create_table.rc == 0